ScavStation/ScavStation

maps/tradeship/tradeship-1.dmm, maps/tradeship/tradeship-2.dmm
- Added a body scanner to medical.
- Added a surgery kit to medical.
- Expanded medical a little bit to fit.
- Added a tokamak, fuel compressor, fuel injector and gyrotron to the burn chamber. Added fusion consoles to the observation room. The gyrotron is too tiny to actually hit fusion temperature currently, but you could conceivably fire the nuclear reactor into it directly to get it started. I'll revisit it tonight.
=> Updated tradeship surgery and engineering.

maps/tradeship/tradeship_jobs.dm
Also adds some stuff to Junior Engineer (belt, gloves, radio).
=> Robustifies yinglet clothing fallbacks.

baystation12.dme, code/__defines/webhooks.dm, code/controllers/subsystems/initialization/persistence.dm, code/game/area/areas.dm, code/modules/multiz/movement.dm, code/modules/projectiles/gun.dm, code/modules/webhooks/webhook_elevator_fall.dm, maps/tradeship/tradeship_areas.dm
Also stops guns killing you when safety is on during a suicide attempt.
=> Added an elevator fall webhook.

code/modules/mob/living/carbon/human/human.dm, code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm, code/modules/species/tradehouse/yinglet.dm, code/modules/species/tradehouse/yinglet_organs.dm
- Yings can now eat wood, blue, napalm, thermite, bunch of inedible stuff. Yum yum.
- Yings bread puking is now a bit more nuanced. They won't digest it at all, and won't get nutrition from it.
=> Ying stomach tweaks.

maps/tradeship/tradeship-1.dmm, maps/tradeship/tradeship-2.dmm
- moved mats from Fabrication to the cargo elevator room.
- moved the YouTool from tool storage to cargo upper level.
- moved the robot cryopod from Fabrication to the tool storage room.
- added a prosthetics and robotics fab to Fabrication.
- added a mining drill and brace to cargo elevator room.
=> Tweaked fabrication and cargo map.

code/modules/species/station/station.dm
=> Added placeholder human lore blurb.

baystation12.dme, code/_helpers/global_access.dm, code/modules/codex/categories/category_fusion_reaction.dm, code/modules/power/fusion/fusion_reactions.dm, test/run-test.sh
=> Added a fusion reaction codex category.

code/game/machinery/rechargestation.dm
=> Added a mousedrag proc to robot rechargers.

code/modules/species/tradehouse/yinglet.dm
Should resolve problems with shock instantly being higher than max HP.
Resolves #39.
=> Increased yinglet max HP twofold.

code/controllers/subsystems/throwing.dm, code/controllers/subsystems/timer.dm, code/game/machinery/alarm.dm, code/modules/atmospherics/components/unary/vent_scrubber.dm, code/unit_tests/map_tests.dm, code/unit_tests/unit_test.dm, code/unit_tests/~unit_test_subsystems.dm
The timer thing is the most important part, but the rest should fix random Travis fails or air alarm problems.
=> Backports some fixes to radio components in vents/scrubbers.

code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm, code/modules/reagents/Chemistry-Recipes.dm
DNM, cannot test till I'm home.
=> Added a reaction to let yings soften up bread to make it edible.

code/game/movietitles.dm
=> Centers credits.

code/modules/reagents/reagent_containers/food/snacks.dm
=> Cheetos don't make scavs sick!

code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
Still to do:
- clam mobs
- clam meat
- clam recipes
=> Added a slime meat reagent for yings to enjoy.

code/datums/supplypacks/galley.dm, code/modules/reagents/reagent_containers/food/fish.dm
=> Buffs the seafood crate.

code/game/machinery/computer/computer.dm, code/game/machinery/doors/airlock.dm, code/game/machinery/vending.dm, code/modules/codex/entries/engineering.dm, code/modules/codex/entries/machinery.dm, code/modules/power/fusion/consoles/_consoles.dm
* Added entry on Hacking.
* Added entry on solar arrays and setup.
* Added entry on cables and cable laying.
* Re-arranged machinery.dm in alphabetical order
* Added entry on airlocks.
* Added entry on computers
* Added entry on modular computers (needs more work)
* Added entry on cryopods
* Added entry on fusion reactor machines, including injectors, core, gyrtron and fuel compressor.
* Added entry on SMES.
* Added entry on suit storage unit.
* Added entry on vending machines.
=> Added several codex entries. Mostly machinery/engineering stuff.

code/modules/codex/categories/category_fusion_reaction.dm
=> Critical typo fix.

code/controllers/subsystems/jobs.dm, code/modules/mob/new_player/new_player.dm
=> Removes redundant wheelchair spawn.

code/modules/mob/living/carbon/human/human.dm
Without causing too many other issues, hopefully.
=> Fixes Rejuvenate/Changeling Revive destroying markings.

code/modules/mob/grab/grab_object.dm
=> You can no longer initiate a grab when you or the target are buckled.

baystation12.dme, code/game/machinery/vending.dm, code/modules/reagents/reagent_containers/food/drinks/juicebox.dm
Thanks for the icons, they are really cute.
=> Implements juiceboxes.

code/modules/mob/living/carbon/human/life.dm
Thanks @Leshana for the original PR (to Bay).
=> Switches health dolls to use a mutable appearance.

code/datums/vote/restart.dm, code/datums/vote/transfer.dm
=> Fixes restart logic so players can call restart or transfer

maps/tradeship/tradeship-2.dmm
=> Moves a fire alarm in engineering.

code/modules/mob/living/living_maneuvers.dm
=> Reflexively performing a maneuver will now clear your prepared maneuver.

baystation12.dme, code/datums/music_tracks/scavs.dm, maps/tradeship/tradeship_define.dm
doot doo doot doo doo doo doot doo doot doo
=> Added a new lobby song for scavmap.

code/_helpers/mobs.dm, code/modules/nano/interaction/default.dm
=> Added helper proc for interpreting non-numerical views.

code/game/machinery/newscaster.dm, code/modules/modular_computers/computers/subtypes/dev_pda.dm, code/modules/reagents/reagent_containers/syringes.dm
- Fixes syringe injections.
- Fixes PDA scanners.
Closes #115.
=> Updating item flags.

maps/tradeship/tradeship-0.dmm
WIP work on the Enclave meeting chamber where matriarch/patriarchs/specialists spawn. Feel free to modify!
=> Enclave meeting chamber WIP

code/game/machinery/cryopod.dm
This brings them into line with the regular cryopods, more or less.
=> Lowered lifepod timeout.

maps/tradeship/tradeship-0.dmm, maps/tradeship/tradeship-1.dmm
* Added lots of trash. Thats it.
* I added a bunch of stuff I didn't want to write every single bit down
* Somewhat fixes elevator
* Adds off-centre stairs.
* Moves janitor stuff from tool storage to enclave deck
=> Furnished enclave deck

code/modules/species/tradehouse/yinglet.dm
=> Removed broken autohiss syllable from yings.

code/game/jobs/job/silicon.dm, code/modules/mob/transform_procs.dm
=> Workaround for robot spawning being busted.

code/modules/client/preference_setup/matchmaking/matchmaking.dm
=> Changes roundstart matchmaking link

code/modules/reagents/reagent_containers/food/drinks/juicebox.dm, code/modules/reagents/reagent_containers/food/fish.dm, maps/tradeship/tradeship-0.dmm
=> Couple of small fixes.

code/_helpers/mobs.dm, code/_onclick/click.dm, code/modules/admin/buildmode/areas.dm, code/modules/mob/living/carbon/human/human_helpers.dm, code/modules/nano/interaction/default.dm, code/modules/nano/interaction/view.dm
=> Trying to cover the client.view problem more thoroughly.

maps/tradeship/tradeship.dm, maps/tradeship/tradeship_antagonists.dm, maps/tradeship/tradeship_lobby.dm
Closes #114.
TC numbers are serverside config rather than code side.
=> Added some antag spawn overrides for Tradeship.

.dockerignore, Dockerfile, docker-compose.yml, tools/indentation.awk
* Update the `Dockerfile` this change allows it to perform tests by building against the `tester` build target, the `spacestation` target will build an optimized version of the game ready for hosting, discarding all source code otherwise present in the build context.
* Do not discard the `.travis.yml` file from `.dockerignore` file since a test exists that asks if all maps are included here. 
* Add `unzip` to required test prerequisites
* Fix a minor error in the awk script `indentation.awk` which caused a break in the docker container.
=> Continuous Integration: Update the Dockerfile

code/game/machinery/doors/airlock.dm, test/check-paths.sh
=> Made airlock interactions with fireaxes slightly more informative.

maps/tradeship/tradeship-2.dmm
=> Adds a wrench to the shuttle

maps/tradeship/tradeship_areas.dm
=> Adds radiation shielding to Ivenmoth shuttles.

code/modules/client/preference_setup/loadout/lists/eyegear.dm, code/modules/clothing/glasses/eyepatch.dm
SCI-patches! They're iPatch items that use the science HUD. They also appear in the loadout file.
=> Adds SCIpatches

code/modules/mob/holder.dm, code/modules/species/tradehouse/yinglet.dm
Don't ask me, I found it in my commit history.
=> Yinglets go 'eee' when used inhand.

code/modules/tables/tables.dm
=> Removes a couple extraneous defines/undefs.

maps/tradeship/tradeship_jobs.dm
* Specificially increases max skill to expert
For #188
=> Increases Matriarch max skill for anatomy

code/modules/species/species.dm
This should make the cavity size unit test redundant.
=> Added automatic organ resizing for species.

code/modules/clothing/clothing.dm
=> Allowed scavs to wear earrings. Lipstick on a pig, really.

code/game/antagonist/outsider/wizard.dm, code/modules/clothing/clothing.dm, code/modules/clothing/clothing_accessories.dm
Use a sharp item on a uniform to shred it.
Closes #172
=> Added a method to tear clothes into rags.

code/modules/fabrication/designs/general/designs_engineering.dm, code/modules/power/solar.dm
* Also assigns a matter value of 4,000 steel to solar assemblies
=> Adds solar assembly to autolathe

code/game/objects/items/weapons/material/coins.dm
* Prevents chat spam
* Adds very mild suspense
=> Adds 1sec cooldown to coin flipping

code/game/objects/items/trash.dm, code/modules/mob/holder.dm, code/modules/mob/living/carbon/human/unarmed_attack.dm, code/modules/organs/internal/stomach.dm, code/modules/reagents/reagent_containers/food/drinks.dm, code/modules/reagents/reagent_containers/pill.dm, code/modules/species/outsider/shadow.dm, code/modules/species/outsider/starlight.dm, code/modules/species/species.dm, code/modules/species/station/golem.dm, code/modules/species/station/monkey.dm, code/modules/species/station/station.dm, code/modules/species/tradehouse/baxxid.dm, code/modules/species/tradehouse/yinglet.dm, code/modules/species/tradehouse/yinglet_organs.dm
=> Various species fixes.

code/game/objects/items/weapons/material/shards.dm, code/game/objects/items/weapons/storage/boxes.dm, code/game/objects/items/weapons/tools/crowbar.dm
* Has a very high chance to break when used to open airlocks
* Has a lower chance to break when used on other things
=> Adds new cheap prybars to survival box

code/modules/mob/skills/skill.dm
=> Clarifies legalese acquirement in bureaucracy skill description

code/modules/mob/living/silicon/robot/modules/module_medical.dm, code/modules/reagents/reagent_containers/dropper.dm
Another victim of the newspaper-can-smack-people change of 2020.
Closes #235.
=> Fixing droppers.

code/modules/turbolift/turbolift_console.dm, maps/tradeship/tradeship-1.dmm, maps/tradeship/tradeship-2.dmm, maps/tradeship/tradeship-3.dmm, maps/tradeship/tradeship_areas.dm, maps/tradeship/tradeship_shuttles.dm
* Added railings to lower cargo elevator shaft
* Replaced plaque with Ivenmoth floor decal
* Added a bunch of stuff to ship roof, including cargo lift access.
* Changes elevator tiles to something slightly less dark
* Also added sound effect to pushing lift button
* Replaced one of the dorm rooms with a drunk tank
=> Map changes, mostly

code/modules/power/fusion/consoles/core_control.dm, code/modules/power/fusion/consoles/injector_control.dm, code/modules/power/fusion/fuel_assembly/fuel_assembly.dm, code/modules/power/fusion/fusion_reactions.dm
=> Fixes problems with fuel rods.

code/modules/turbolift/turbolift.dm, code/modules/turbolift/turbolift_map.dm, maps/tradeship/tradeship_shuttles.dm
=> Tradeship turbolift plays sounds when moving.

maps/tradeship/tradeship-0.dmm
=> Adds drains to enclave level.

code/modules/overmap/spacetravel.dm
Possibly New/Initialize-related, has a number of problems regardless.
=> Fixes lost in space sometimes moving you to the overmap.

code/modules/reagents/reagent_containers.dm
=> Fixes reagent amounts.

code/__defines/items_clothing.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/mob.dm, code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm, code/modules/species/species.dm, code/modules/species/tradehouse/yinglet.dm, code/modules/species/tradehouse/yinglet_accessories.dm, code/modules/sprite_accessories/_accessory.dm, code/modules/sprite_accessories/_accessory_hair.dm
Hair remover will set ying body colour to a skin shade and remove any hair-based markings like tail tufts.
Closes #284.
=> Expanded the effects of hairloss to include yinglets.

code/game/objects/structures.dm, code/game/objects/structures/girders.dm, code/game/objects/structures/grille.dm
=> Removed some extra material drops from grilles and girders.

code/game/objects/items/weapons/material/shards.dm, code/game/objects/structures/__structure.dm, code/game/objects/structures/_structure_materials.dm, code/game/objects/structures/barricade.dm, code/game/objects/structures/girders.dm, code/game/objects/structures/grille.dm, code/game/objects/structures/stool_bed_chair_nest/chairs.dm, code/game/objects/structures/window.dm, code/modules/persistence/noticeboards.dm, code/modules/tables/rack.dm, maps/antag_spawn/heist/heist_base.dmm, maps/antag_spawn/mercenary/mercenary_base.dmm, maps/away/bearcat/bearcat-2.dmm, maps/away/casino/casino.dmm, maps/away/icarus/icarus-1.dmm, maps/away/icarus/icarus-2.dmm, maps/away/lar_maria/lar_maria-2.dmm, maps/away/lost_supply_base/lost_supply_base.dmm, maps/away/magshield/magshield.dmm, maps/away/mining/mining-signal.dmm, maps/away/unishi/unishi-2.dmm, maps/random_ruins/exoplanet_ruins/hydrobase/hydrobase.dmm, maps/random_ruins/exoplanet_ruins/lodge/lodge.dmm, maps/random_ruins/exoplanet_ruins/marooned/marooned.dmm, maps/random_ruins/exoplanet_ruins/oldpod/oldpod.dmm, maps/random_ruins/exoplanet_ruins/playablecolony/colony.dmm, maps/tradeship/tradeship-0.dmm, maps/tradeship/tradeship-2.dmm
Fixes #303.
Fixes #304.
Fixes #305.
Fixes #306.
Fixes #307.
Fixes #309.
Fixes #310.
=> Material/structure fixes.

code/modules/reagents/Chemistry-Grinder.dm, nano/templates/rgrinder.tmpl, test/check-paths.sh
Fixes #317 
- Reagent Grinder has an updated NanoUI.
=> New Grinder UI + interact adjacency bugfix

code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm, code/modules/reagents/Chemistry-Recipes.dm, code/modules/reagents/reagent_containers/food/snacks.dm
- Removes or replaces /drink reagents from bread items.
- Adds banana cream and a banana cream recipe.
These are all the ones I could find at a once-over of the bread food items.
Fixes #324.
=> Fixes soggy food.

code/controllers/subsystems/initialization/materials.dm, code/modules/codex/categories/category_fusion_reaction.dm
Also adjusts some misplaced tabs in fusion reaction generation.
Fixes #301.
Fixes #302.
=> Amends fusion reaction codex template to have correct temperature.

code/datums/supplypacks/galley.dm, code/game/machinery/vending.dm, code/game/objects/items/weapons/storage/boxes.dm, code/game/objects/random/random.dm, code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm, code/modules/reagents/Chemistry-Recipes.dm, code/modules/reagents/reagent_containers/food/cans.dm, code/modules/reagents/reagent_containers/food/drinks/bottle.dm, code/modules/reagents/reagent_containers/food/lunch.dm, maps/antag_spawn/wizard/wizard_base.dmm, maps/away/casino/casino.dmm, maps/random_ruins/exoplanet_ruins/crashed_pod/crashed_pod.dmm
=> alcohol description and title fixes

code/__defines/misc.dm, code/modules/library/skill_books.dm
* Better title selection
* Various minor fixes and tweaks
* Added "Add Article" to __defines
=> Tweaks and fixes to skill books

code/game/machinery/Sleeper.dm, code/game/objects/items/weapons/storage/med_pouch.dm, code/modules/clothing/masks/chewable.dm, code/modules/clothing/spacesuits/rig/modules/utility.dm, code/modules/culture_descriptor/culture/cultures_human.dm, code/modules/genetics/side_effects.dm, code/modules/materials/definitions/materials_gasses.dm, code/modules/reagents/Chemistry-Grinder.dm, code/modules/reagents/Chemistry-Recipes.dm, code/modules/reagents/chems/chems_elements.dm, code/modules/reagents/chems/chems_medicines.dm, code/modules/reagents/dispenser/cartridge_presets.dm, code/modules/reagents/dispenser/dispenser_presets.dm, code/modules/reagents/reagent_containers/borghydro.dm, code/modules/reagents/reagent_containers/pill.dm, code/modules/species/station/station.dm
DNM WIP
- Fixes issues with oxygen being a fake chem for nerds.
- Fixes #344.
- Fixes #350.
=> Various fixes.

code/datums/communication/pray.dm, code/modules/admin/topic.dm
Cookie spawning via pray has been completely replaced with clam spawning.
=> Adminspawncookie is now adminspawnclam like god intended

code/_onclick/click.dm, code/_onclick/hud/_defines.dm, code/_onclick/hud/action.dm, code/_onclick/hud/deity.dm, code/_onclick/hud/movable_screen_objects.dm, code/_onclick/hud/robot.dm, code/datums/cinematic.dm, code/game/gamemodes/endgame/nuclear_explosion/nuclear_explosion.dm, code/game/movietitles.dm, code/game/objects/items/weapons/storage/storage_ui/default.dm, code/modules/admin/buildmode/buttons.dm, code/modules/client/client_procs.dm, code/modules/lighting/lighting_planemaster.dm, code/modules/mechs/interface/_interface.dm, code/modules/mob/living/simple_animal/borer/borer_hud.dm, code/modules/psionics/interface/ui_hub.dm, code/world.dm
This shoooould(?) solve the weird offsetting problems people were getting at high icon sizes. Won't fix the overlapping UI, though.
=> Converted UI to use directional flags not cardinal.

maps/tradeship/tradeship-0.dmm, maps/tradeship/tradeship-1.dmm, maps/tradeship/tradeship-2.dmm, maps/tradeship/tradeship-3.dmm, maps/tradeship/tradeship_areas.dm
-Purpose - improve security for engineering
-Switched tool vendor locations in tool storage
-Added a wall and removed a wall in tool storage, changed access credentials for interior tool storage door
-Moved a few doors and associated utility lines
=> Toolshop reworking for improved engineering security

code/game/jobs/access.dm, code/modules/departments/department.dm, code/modules/departments/standarddepartments.dm, code/modules/modular_computers/file_system/programs/command/card.dm, nano/templates/identification_computer.tmpl
=> Redid ID comp UI for new dept system.

maps/shelltooth/shelltooth-2.dmm, maps/shelltooth/shelltooth-4.dmm, maps/shelltooth/shelltooth.dm, maps/shelltooth/shelltooth_items.dm
matriarch's shuttlequarters and a basic cargo added.  Various wirings added to floors 2 and 4.  Mapmerged this time.  I hope this is the last PR for shelltoothmountainmine.  I hope this for all of us.
=> map workings with real merging action

config/example/motd.txt
=> Update example motd

code/game/movietitles.dm, code/modules/webhooks/webhook_roundend.dm
Real talk, I didn't test this.
=> End-of-round webhook now shows the episode title.

code/modules/organs/external/diagnostics.dm, code/modules/organs/internal/_internal.dm
Except, by some inexplicable black magic, when they're not attached.
Also fixed a minor grammatical error with exposed bones.
=> Makes organs tell you if they're crystalline, assisted, or mechanical, when seen through gaping wounds.

maps/shelltooth/shelltooth-1.dmm, maps/shelltooth/shelltooth_areas.dm
* Furnished Library
* Furnished Hydroponics
* Changed Hydroponics name to "Plant House"
* Tweaked Kitchen and Cafe
=> Shelltooth progress: Library, Hydro, Cafe

code/content_packages/valsalia/items/egg_yinglet.dm
My mistake, I broke Winter's code.
=> Fixed layering issue with yingegg.

maps/shelltooth/shelltooth-3.dmm, maps/shelltooth/shelltooth-4.dmm
new rooms and utility lines, items added to communications relay, storage, and brig.
=> worked on top 2 floors

maps/shelltooth/shelltooth-0.dmm, maps/shelltooth/shelltooth-1.dmm, maps/shelltooth/shelltooth-2.dmm, maps/shelltooth/shelltooth-3.dmm, maps/shelltooth/shelltooth-4.dmm
Add this AFTER clamchowdermountainminereturns.  I re-prepared maps after completing that PR, so for a complete map-change narrative, probably for the best to keep both?
=> Plumbingwithscavs

maps/shelltooth/shelltooth-3.dmm, maps/shelltooth/shelltooth-4.dmm
incomplete changes but let's get 'em merged and I'll add to it later
=> reworked some rooms in executive floor, added content to science rooms

maps/shelltooth/shelltooth-0.dmm, maps/shelltooth/shelltooth-1.dmm, maps/shelltooth/shelltooth-3.dmm, maps/shelltooth/shelltooth-4.dmm
-Mostly just updating to current codebase.
-Also added fire alarms and other room necessities in a number of locales.
=> Miracleatthemountainmine

maps/shelltooth/shelltooth-0.dmm, maps/shelltooth/shelltooth_unit_testing.dm
=> Furnished custodial closet and garbage disposal

maps/ministation/ministation.dmm, maps/ministation/ministation_areas.dm
* Altered security heavily and made smaller.
* Added a court room
* Added two maint areas, one for sec and one for forensics
=> Ministation Changes: The Court Of Law

mods/valsalia/species/yinglet.dm
=> Fixed some issues with ying squeaking.

maps/tradeship/tradeship-0.dmm
added clothing to enclave level, added minor scavproofing to the disposals unit to prevent avoidable accidents.
=> Added a few clothing articles to enclave level

code/_helpers/medical_scans.dm, code/controllers/configuration.dm, code/modules/organs/blood.dm, mods/species/adherent/datum/species.dm, mods/species/utility_frames/species.dm
Updates from nebula staging
various fixes
nebula devs
:cl:
fix: fixed a few things
/:cl:
=> Nebulaupdate

maps/tradeship/tradeship_define.dm
Increased spawn rate for exoplanets and away sites
More stuff to do in rounds
Qumefox
:cl:
tweak: Away site and exoplanet spawn rates
/:cl:
=> Away site and exoplanet spawn rate change

maps/tradeship/tradeship-0.dmm, maps/tradeship/tradeship-2.dmm, mods/valsalia/map/loadout.dm
Added a freezer to the medbay
Added Tailglove to the medbay
Added 2 trashbags to the enclave floor
Added fancy clothes, fancy hat, yinglet apron, yinglet jacket to the laundry room
Added Fancy clothes, fancy hat, yinglet jacket, yinglet apron, and small cape to character creation
Makes life somewhat easier for doctors
also more clothing is available
Whoever added in clothing before
Devchord helped too
:cl:
add: added freezer to medbay
add: added various clothing to the map
add: added new clothing options to character creator
/:cl:
=> Freezer and clothing

maps/away/liberia/liberia.dmm, maps/tradeship/tradeship-2.dmm, maps/tradeship/tradeship-3.dmm, maps/tradeship/tradeship_areas.dm
Switched the Libaria and the Mule to run on rocket thrusters instead of ion
Changed tradeship's antag room into a storage room as a placeholder
fixed door permissions for the new library
This will make the life of any unfortunate person who spawns on the Liberia less dull
Devchord
:cl:
add: Added rocket thrusters to the liberia and the mule
/:cl:
=> Devcord edits

maps/away/liberia/liberia.dmm, maps/tradeship/tradeship-2.dmm, maps/tradeship/tradeship-3.dmm, maps/tradeship/tradeship_areas.dm
Reverts ScavStation/ScavStation#597
This apparently had the tradeship changes too, not just the liberia changes
=> Revert "Devcord edits"

code/modules/reagents/Chemistry-Holder.dm, code/modules/reagents/reactions/_reaction.dm
Mirror of https://github.com/NebulaSS13/Nebula/pull/2671, hopefully fixes some chem issues.
=> Added some value clamping to reagent total updates.

maps/away/unishi/unishi-3.dmm, mods/valsalia/items/voidsuits.dm
Added a new yingsuit for the crew of the  Verne and placed them within the emergency closets
New yingsuits added for the SRV Verne
Well, to put it simply, this makes this spawn viable.
Devchord
:cl:
add: Added a voidsuit for the SRV Verne
/:cl:
=> Unishi yingsuits

maps/tradeship/tradeship-2.dmm, maps/tradeship/tradeship_areas.dm, maps/tradeship/tradeship_shuttles.dm
adds rescue shuttle to tradeship starboard docking port
backup transportation FTW
Qumefox
:cl:
add: rescue shuttle
/:cl:
=> added rescue shuttle

maps/tradeship/tradeship_overmap.dm, maps/tradeship/tradeship_shuttles.dm
hopefully fixes exploration shuttle
because it didn't work for some reason after adding the rescue shuttle
Qumefox
:cl:
fix: fixed a few things
/:cl:
=> hopefully makes the original shuttle work again

code/__defines/maths.dm, code/game/turfs/turf_fluids.dm, code/modules/multiz/movement.dm, code/modules/organs/blood.dm, code/modules/reagents/Chemistry-Holder.dm, code/modules/reagents/reactions/_reaction.dm
Reverts ScavStation/ScavStation#636
=> Revert "Crashfix"

code/__defines/maths.dm, code/game/turfs/turf_fluids.dm, code/modules/multiz/movement.dm, code/modules/reagents/Chemistry-Holder.dm, code/modules/reagents/reactions/_reaction.dm
Reverted erroneously due to the blood bug.
=> Readds rounding fixes

nano/templates/fabricator_bioprinter.tmpl, nano/templates/fabricator_robot.tmpl, nano/templates/fabricator_shared.tmpl
May fix lathe errors on IE10 and lower (https://github.com/ScavStation/ScavStation/issues/624).
=> Swaps let to var in fab templates.

tools/ReplicateSaves/README.md, tools/ReplicateSaves/replicate_saves.py
Save copy script
copy player saves from tradeship to other maps
Mistakenot
:cl:
add: save copy script
/:cl:
=> Added a Python script for replicating player saves for all other maps.

maps/ministation/ministation.dmm, maps/ministation/ministation_areas.dm
This update adds in the supermatter engine onto ministation as well as ATMs and sawed off shotguns for security
supermatter will provide more gameplay for engis, the ATM will help cargo, and the sawed off shotguns will help sec
Devchord
:cl:
add: Added Supermatter Engine into engineering
add: Added ATMs around the station
add: Added sawed off shotguns for security
add: Added fancy office chairs to a couple of places around the station
/:cl:
=> Minstationfixes112522

code/modules/paperwork/faxmachine.dm
trying to make this shit work. take 3.
see above
my idiot self.
:cl:
fix: fixed a few things maybe
/:cl:
=> moved webhook to the admin msg section. round 3, COMMIT

maps/ministation/ministation.dmm, maps/ministation/ministation_areas.dm, maps/ministation/ministation_overmap.dm, maps/ministation/ministation_shuttles.dm, maps/ministation/ministation_unit_testing.dm
A science shuttle was added to R&D to allow the exploration of away sites, also a faulty airlock was fixed
Will give more incentive for players to take part in the wonderful field of science
Devchord
:cl:
add: added a Science shuttle
fix: fixed cargo airlock
/:cl:
=> ScienceShuttle

maps/ministation/jobs/civilian.dm, maps/ministation/jobs/science.dm, maps/ministation/jobs/security.dm, maps/ministation/ministation.dmm
Added in EVA equipment for mining as well as opened up EVA for all department heads and cargo
its hard for cargo to mine without the proper equipment, also it seems silly that HoS and RD cant access the EVA equipment
Devchord
:cl:
add: Jetpack and oxygen tank for mining
add: Added EVA Access to department heads and cargo
/:cl:
=> Ministation fixes 1 5 23

mods/valsalia/species/yinglet.dm
=> Fixes yinglets going albino when irradiated.

maps/ministation2/jobs/command.dm, maps/ministation2/ministation-0.dmm, maps/ministation2/ministation-1.dmm, maps/ministation2/ministation-2.dmm, maps/ministation2/ministation_areas.dm, maps/ministation2/outfits/medical.dm
Bug/Map fixes for ministation2
QoL stuff to keep the game running smooth
Devchord
:cl:
add: added organ freezer in operating theater
add: added holster and void suit in matriarchs room
add: added headsets for Junior Doctors
add: added atmospherics access for hop
add: added chief engineer's locker to engineering
add: added proper airlock for the meat freezer
add: added a bell for medical reception
add: Added a trash collection room for janitors
del: deleted the wall blocking cargo smelter
fix: fixed broken light switches in the SM control room
fix: fixed stairwell camera placements
fix: fixed fireaxe placement on the bridge
/:cl:
=> planned fixes

maps/ministation2/jobs/civilian.dm, maps/ministation2/jobs/security.dm, maps/ministation2/ministation-0.dmm, maps/ministation2/ministation-1.dmm, maps/ministation2/ministation-2.dmm, maps/ministation2/ministation_objects.dm
Simplified SM airlock and buttons
reorganized cameras to be less cluttered
added Hos access to Hos
gave EVA access to cargo only now because im an idiot
Makes the station just a tiny bit more functional
Devchord
:cl:
add: hos access to hos
add: eva access to cargo
del: Removed button from SM ejection airlock
tweak: renamed buttons on sm eject to make SM ejection possible
fix: fixed up the camera network list to be less cluttered
/:cl:
=> Ministation2fixes 3 1 23

maps/ministation2/ministation-0.dmm, maps/ministation2/ministation-1.dmm, maps/ministation2/ministation-2.dmm
Nothing really substantial with these fixes namely, 3 things were changes, plant clippers were added to xenobotany and hydroponics, missing emergency shutters were added to all interior doors and maintenance hatches, colored floor tiles in front of the bridge and engineering were adjusted
Safety junk and Science crap, the real bread and butter here is some feel good aesthetics
Devchord
:cl:
add: Added plant clippers to xenobotany
add: Added plant clippers to hydroponics
add: Added many missing firedoors
fix: fixed colored tile placement in front of the bridge and engineering
/:cl:
=> Ministation2fixes3 23 23

maps/ministation2/ministation-0.dmm, maps/ministation2/ministation-1.dmm, maps/ministation2/ministation-2.dmm
Reverts ScavStation/ScavStation#709 at the request of devcord
=> Revert "Ministation2fixes3 23 23"

maps/ministation2/jobs/security.dm, maps/ministation2/ministation-0.dmm, maps/ministation2/ministation-1.dmm, maps/ministation2/ministation-2.dmm, mods/valsalia/_valsalia.dme, mods/valsalia/items/supply.dm, mods/valsalia/items/voidsuits.dm
Modernized R&D to allow for exosuit construction as well as added mining and atmos variants of the yinglet voidsuit. Also added in drone fabricators
Drones are playable again, and Science will have a better time doing their science
Devchord
:cl:
add: Added small mining voidsuit
add: Added small atmospherics voidsuit
add: Added Osmium to the materials supply
add: Added maintenance drone fabricator to the west engineering maintenance
add: Added construction drone fabricator to the east engineering maintenance
add: Added missing fabricators to R&D
add: Added a small EVA room to R&D
add: Added an exosuit room to R&D
balance: replaced hallway exterior windows with reinforced windows
fix: fixed security not having access to the law office
fix: fixed the trash room being a "janitors only" area …
=> Ministation2 fixes 4 12 23

maps/ministation2/ministation-0.dmm, maps/ministation2/ministation-1.dmm, maps/ministation2/ministation-2.dmm, maps/ministation2/ministation-3.dmm
Added several rooms to the station and edited a few work spaces and some hallways
Have tested the edited areas and made corrections where possible.
=> Map Changes Sec, Med and Sci

maps/ministation2/ministation-1.dmm, maps/ministation2/ministation-2.dmm, maps/ministation2/outfits/science.dm, maps/ministation2/outfits/security.dm
Light switch was added to RD office, Bar shotgun now has beanbag shells at the start, Bar/hydro door can be viewed through now. Some cameras and lights were moved around. Security Officers and Researchers will now start with their respective department headset
General fixes to help gameplay
Devchord
:cl:
add: Added light switch to RD office
add: Added missing department headsets to Researcher and Security roles
add: Replaced hydro/bar door
balance: rebalanced bar from having lethal ammunition to less-than lethal
fix: fixed placement of some lights and cameras
/:cl:
=> Ministation2fixes 5 24 23

maps/ministation2/ministation-0.dmm, maps/ministation2/ministation-1.dmm
Fixed double door positioning
Immersion
Devchord
:cl:
fix: fixed double door positioning in cargo, engineering, and medical
/:cl:
=> Ministation2 fixes 6 29 23

maps/ministation2/ministation-1.dmm, maps/ministation2/ministation-2.dmm
Fixed shuttle double door to look proper, added suspension field circuitboard to xenoarch, added some honey for the kitchen
Functionality or something like that, maybe a little bit of immersion too?
Devchord
:cl:
add: Added suspension field circuit board to xenoarch
add: Added honey packets to the kitchen
fix: fixed science shuttle door
/:cl:
=> Ministation2 fixes 7 7 23

maps/ministation2/ministation-0.dmm
Fixed door in satellite
immersion
Devchord
:cl:
fix: fixed double door position on the ai satellite
/:cl:
=> ministation2fixes-8-4-23

maps/ministation2/ministation-0.dmm
Fixed the TEG position and pump so engineers don't have to make this change every round.
Added BOOZE to the booze dispenser so grumpy HoS's will still have to steal all access for a glass of devil's rain to make the day better.
=> Engineering changes

maps/ministation2/ministation-1.dmm
Added kitchen sink to bar to help improve the working conditions for barkeeps
Bar RP
Devchord
:cl:
add: Added kitchen sink to bar
/:cl:
=> ministation2fixes-9-8-23

maps/ministation2/ministation-0.dmm, maps/ministation2/ministation-1.dmm, maps/ministation2/ministation-2.dmm, maps/ministation2/ministation_define.dm
fixed telecomm channels (only for headsets, intercomms are going to need more time)
various other minor map fixes
Makes more than one channel for communication, the other map changes are QoL
Devchord
:cl:
add: Added disposal system to library
add: Added extra light to engineering hallway
add: Added light switches to offices
tweak: tweaked start positions for some department heads
fix: fixed telecomms not being defined in ministation-define
fix: fixed chairs being bolted in the wrong direction on the bridge and in telecomms
fix: fixed network not being called tradenet
/:cl:
=> Ministation2fixes 9 15 23

maps/ministation2/ministation-2.dmm, maps/ministation2/ministation_jobs.dm
Fixed airless plating in library
Added more jobs for baxxid
Makes librarian and baxxid gameplay better
Devchord
:cl:
add: Added more jobs to baxxid whitelist
fix: fixed open space under library airlock
/:cl:
=> Ministation2fixes 9 21 23

maps/ministation2/ministation-1.dmm, maps/ministation2/ministation-2.dmm
fixed initial network for tcomms and science
also fixed some sign positioning and the floor in tcomms
makes tcomms work at the start of the game
Devchord
:cl:
fix: fixed initial network access for telecomms and research
fix: fixed some sign positioning being misalligned
fix: fixed pipes being visible through telecomms floor
/:cl:
=> Ministation2fixes 9 23 23

maps/ministation2/ministation-0.dmm, maps/ministation2/ministation-1.dmm, maps/ministation2/ministation-2.dmm, maps/ministation2/ministation-3.dmm, maps/ministation2/ministation_areas.dm, maps/ministation2/ministation_unit_testing.dm
Maintenance corridors are now all linked together. Ai has access to more cameras and drone fabricators. Cargo has a new lobby now. 
Ai is more playable and some QoL changes for cargo
Devchord
:cl:
add: Added new areas for maintenance overpass and underpass
add: Added expanded cargo lobby
add: Added extra security cameras around the station
balance: set most shutters starting state to closed
/:cl:
=> Ministation2fixes 10 19 2023

maps/random_ruins/exoplanet_ruins/crashed_pod/crashed_pod.dmm
added welding fuel tank and plaque to crashed pod.
Because I forgot them originally
:cl:
add: Added fueltank and plaque to pod
/:cl:
=> add fueltank to crashed pod

maps/ministation2/ministation-0.dmm, mods/valsalia/map/culture.dm, mods/valsalia/map/culture_baxxid.dm, mods/valsalia/species/baxxid.dm, mods/valsalia/species/indrel.dm, mods/valsalia/species/yinglet.dm
Added more background options for yinglets, also added a background location for baxxid and indrel
Immersive RP stuff
Devchord
:cl:
add: Added new culture backgrounds for yinglets
add: Added a new culture background for baxxid
add: Added a new culture background for indrel
add: Added missing lights in atmos
/:cl:
=> Ministation2 fixes 11 30 23

maps/ministation2/ministation-0.dmm
=> Added network relays to engineering.

code/modules/fabrication/designs/general/designs_general.dm, maps/ministation2/ministation-0.dmm, maps/ministation2/ministation-1.dmm, maps/ministation2/ministation-2.dmm
Nitpicks Tweaked
Access to certain doors have been modified
Security been made MORE secure, in theory. Our unaware test subject shall provide us with results.
More options added to sec for the determined crew that crave a light show from the armory.
Turrets and bolt controls added to the AI core.
While expensive for now, duct tape has been added to the autolathe as a crafting option.
=> Secure-er Update

code/game/jobs/access_datum.dm, maps/ministation2/jobs/command.dm, maps/ministation2/jobs/engineering.dm, maps/ministation2/jobs/medical.dm, maps/ministation2/jobs/science.dm, maps/ministation2/jobs/security.dm, maps/ministation2/jobs/tradehouse.dm, maps/ministation2/ministation-0.dmm, maps/ministation2/ministation-1.dmm, maps/ministation2/ministation-2.dmm, mods/valsalia/items/firesticks.dm
- Added new camera access requirement most departmental cameras have been set to require their own accesses
- Intended functionality of the YAR has been put in place (FINALLY)
- Added ~flavor~ to the armory contents
- Shutters added to OR rooms
- Spawn points renamed, some may still need to be added
=> Hefty changes

code/datums/wires/airlock.dm, maps/ministation2/ministation-0.dmm, maps/ministation2/ministation-1.dmm
Got rid of the magical fountain for a mundane one. Minor fixes with the armory contents and re-added suits in EVA
=> Reopening this since Reverting a commit counts as removing.. maybe

code/datums/vote/map.dm
removes admin requirements for calling for map votes
allows players to call for map changes
Qumefox
:cl:
tweak: map vote restrictions
/:cl:
=> Removes that admin requirement for map votes

mods/valsalia/jobs/yinglet_job.dm
=> Fixes scav redcoats.

maps/ministation2/ministation-2.dmm
Partially addresses #868 but it seems like sensors have broader issues.
=> Added terminals under sensor suites.

mods/valsalia/items/prosthetics.dm
=> FBP yings should now use the same equip adjusts as meat yings.

maps/ministation2/ministation-0.dmm, maps/ministation2/ministation-1.dmm, maps/ministation2/ministation-2.dmm, maps/ministation2/ministation-3.dmm, maps/ministation2/ministation_areas.dm, maps/ministation2/ministation_unit_testing.dm
Multiple departmental changes throughout the station
=> Map Changes

maps/ministation/ministation-0.dmm
Fixs a wall in maint on top of a door.
=> Fuck you wall!

maps/ministation/ministation-1.dmm, maps/ministation/ministation-2.dmm, maps/ministation/ministation-3.dmm, maps/ministation/ministation_areas.dm, maps/random_ruins/exoplanet_ruins/hydrobase/hydrobase.dmm
See title, it fixs some missing roofs too.
=> Fixs the cargo lift doors, and makes the new sci testing zone a bit nicer

maps/ministation/ministation-0.dmm, maps/ministation/ministation-1.dmm, maps/ministation/ministation-2.dmm, maps/ministation/ministation-3.dmm
I forgot a TON of lights.
And fixs the SM doors so it can be yeeted if needed
=> Fixs the D A R K N E S S

maps/ministation/ministation-2.dmm
=> A few fixs in the robot lab

maps/ministation/ministation-0.dmm, maps/ministation/ministation-2.dmm, maps/ministation/ministation-3.dmm
Fixs Engi cams, and Adds cams to deck 4 and new sci.
=> Yinglet Cam Time

maps/ministation/ministation-0.dmm, maps/ministation/ministation-1.dmm, maps/ministation/ministation-2.dmm, maps/ministation/ministation-3.dmm, maps/ministation/ministation_areas.dm, maps/ministation/ministation_unit_testing.dm
Map only changes of the HUG update
=> Second attempt at map changes that broke the first time

mods/valsalia/species/baxxid.dm
Autohnnns statistically calibrated loosely based on scavenged data. Full autohiss mode added, featuring text bolding and random triplication of letters (loosely based on statistical data yet again).
A thicker baxxid accent.
:cl:
add: Baxxid "full" autohiss mode
/:cl:
=> Baxxid full autohisss mode

code/datums/supplypacks/dispcarts.dm, code/modules/reagents/chems/chems_compounds.dm, code/modules/reagents/chems/chems_drinks.dm, code/modules/reagents/dispenser/cartridge_presets.dm, code/modules/reagents/dispenser/dispenser_presets.dm, code/modules/reagents/reagent_containers/condiment.dm, maps/ministation/ministation-1.dmm
-Added Cinnamon reagent and related items
-Added Lavender Syrup reagent and related items
-Renamed Baron Grey to Earl Grey
-Changed London Fog recipe to require vanilla syrup
Adds a few coffee-related items, more options and flavors for the barista
:cl:
add: Cinnamon reagent and related items
add: Lavender Syrup reagent and related items
del: Removed old things
tweak: Renamed Baron Grey to Earl Grey
tweak: Changed London Fog recipe to require vanilla syrup
/:cl:
=> Coffee-related changes

code/modules/clothing/pants/_pants.dm, code/modules/clothing/shoes/_shoes.dm, code/modules/clothing/under/_under.dm
Addresses https://github.com/ScavStation/ScavStation/issues/1008 and various Discord complaints.
I have tested that this gives yinglets fallback uniforms and shoes, I have not tested if it prevents them wearing anything specific.
=> Restricted base pants, shoes and uniforms to humans again.

maps/_map_include.dm, maps/ministation/ministation-1.dmm
-Fixed accidental character in _map_include.dm
-switched doors in medbay to glass
-changed lighting in nursery
-changed an incorrect wall tile in nursery
(note: the pilk correction Mistake called out isnt actually an issue, we discussed it and he was mistaken (hehe, get it cuz thats his name))
Fixed some minor issues with the last PR that were noted by Mistake, and myself while testing
:cl:
bugfix: Fixed accidental character in _map_include.dm
tweak: switched doors in medbay to glass
tweak: changed lighting in nursery
tweak: changed an incorrect wall tile in nursery
/:cl:
=> Fixed Minor Issues with previous changes

mods/species/bayliens/tajaran/_tajaran.dm, mods/species/bayliens/tajaran/datum/species_bodytypes.dm
=> Taj now use humanoid bodyflag.

.gitignore, maps/ministation/ministation-0.dmm, maps/ministation/ministation-1.dmm, maps/ministation/ministation-2.dmm, maps/ministation/ministation-3.dmm, maps/ministation/ministation_areas.dm
Zhe enclave has grown, and zhere are many new zhings to see! Like... Uh... Air tanks. And some engineering zhings. OH! STAIRS! Yes stairs. Very. But yes lots of additions to zhe enclave space, improvements. and some fun setpiece fixes!
=> Enclave enbiggifying!!!

maps/ministation/ministation-0.dmm, maps/ministation/ministation-1.dmm, maps/ministation/ministation-2.dmm, maps/ministation/ministation-3.dmm, maps/ministation/ministation_unit_testing.dm
Fix for access for the intended public Biodome
Added FUN reactor as a back up or alternate source of energy or destruction
Added cameras for a number of new additions without camera coverage.
=> Hotfixes to last addition and small add ons

code/modules/projectiles/guns/energy/laser.dm, maps/ministation/ministation-0.dmm, maps/ministation/ministation-1.dmm, maps/ministation/ministation-2.dmm, maps/ministation/ministation-3.dmm, mods/valsalia/_valsalia.dme, mods/valsalia/items/med_vend.dm
=> Removal of fun thing

maps/ministation/ministation-0.dmm, maps/ministation/ministation-1.dmm, maps/ministation/ministation-2.dmm, maps/ministation/ministation-3.dmm, maps/ministation/ministation_areas.dm
matriarch's chambers
armory
yingjail
eggclave/place-what-female-yings-be-at
todo next time: crush it all smaller and/or crush it crunchily destruction-like because it'll be cool
=> Enclave do an embiggening

code/modules/multiz/level_data.dm
cherry picks mistakenot's solar fix from his nebula PR
fixes solars hopefully
:cl:
bugfix: fixed solar day cycle
/:cl:
=> Moves solar daycycle onto base level data type.

mods/valsalia/species/baxxid.dm
Already did a pull request for this earlier, but to the wrong branch I believe [https://github.com/ScavStation/ScavStation/pull/1131].
=> Alter and buff the baxxid mouth dexterity.

maps/random_ruins/exoplanet_ruins/summit/summit.dmm
summit.dmm tweaks, should be solid, unless something weird is up with some color settings. but probably not.
changes:
-initial temperatures around the map
-tried and failed to fix a color issue with some hoodies
=> Last map update for now

mods/valsalia/_valsalia.dme, mods/valsalia/mobs/buffdrones.dm
Modified drones with More grippable items, ability to craft with materials as well as slightly more plastic panels (from 1 to 12) AI laws now get synced to drones when taking control of it, drones have stronger lamp. Put all changes in buffdrones.dm file.
I think they will allow for more flexibility and usefulness for drones and cyborgs, especially on low-pop rounds.
:cl:
add: Added more items to robotic gripper in Drone and Medical cyborg
add: Added ability to craft from material in construction drones and cyborgs
tweak: Tweaked the light strength and range for drones
tweak: tweaked a plastic synthesizer with extra 11 panels
tweak: tweaked procedure of AI possessing Drone to sync the AI's laws into the drone. 
/:cl:
=> Drone updates attempt 2

.github/workflows/test.yml, install-byond.sh
Horrible hacks by yours truly to fix unit tests on scavstation. 
Uses local repo copy of byond installer for github runners. Non github runners using the script should continue to download directly from byond.com though.
Lets unit tests work again after byond.com apparently blacklisted github from downloading binaries from their site. Also temporarily disables the opendream unit test since scav doesn't use it and I don't know how to fix it.
Qumefox
:cl:
bugfix: fixes unit tests
/:cl:
=> Horrible hacks to fix unit tests

maps/random_ruins/exoplanet_ruins/summit/summit.dm, maps/random_ruins/exoplanet_ruins/summit/summit.dmm
Did some tweaks to summit away site. there might be a biut of dreamchecker error but I tried to make it go away and even then it shouldn't actually affect anything. 
Me and Mairujyat 
:cl:
tweak: tweaked event handling like delay for starting, location notification and win condition. 
bugfix: fixed color tags on map file
/:cl:
=> Tweaks and fixes to Summit event aways site

maps/ministation/ministation_areas.dm, maps/ministation/space.dmm
Updates to Centcomm and Evacuation Shuttle
Increases evacuation shuttle capacity to hold more entities, adds an atmospherics system and minor changes to Centcomm to prevent air loss.
Cegmeister, Olympus7
:cl:
add: Added new things
add: Added more things
/:cl:
=> Update Centcomm and Shuttle

maps/random_ruins/exoplanet_ruins/summit/summit.dm
Check the notes on the commit; Summit should spawn a bit less often
=> Tiny summit update, nothin' major

maps/ministation/ministation-0.dmm, maps/ministation/ministation-1.dmm, maps/ministation/ministation-2.dmm, maps/ministation/ministation_areas.dm
Map changes for the Murphy, applying various changes we've committed to in the past month. Its not complete yet but our work should at least be visible
Progress on the Murphy
:cl:
tweak: added functional atmos
tweak: added medbay
tweak: added bedrooms
tweak: added and modified various other rooms
/:cl:
=> Remodels to Murphy

maps/tradeship_alt/tradeship-1.dmm, maps/tradeship_alt/tradeship-2.dmm, maps/tradeship_alt/tradeship-3.dmm
Map edits and minor fixes. Connects the network to the rest of the ship.
Ship will have a network now.
CEG
:cl:
added: Map fixes
/:cl:
=> Map Edits to Tradeship_Alt

maps/tradeship_alt/tradeship-3.dmm
Fixes a misaligned ladder in the solar array.
You can now use the ladder.
CEG
:cl:
bugfix: fixed a bad ladder
/:cl:
=> Ladder Fix for Fishfinder

maps/tradeship_alt/tradeship-1.dmm, maps/tradeship_alt/tradeship-2.dmm
returned supply closet to its original location
better supply closet area and also railings and stuff
CEG
:cl:
tweak: supply closet
/:cl:
=> bridge fixes and return of the supply closet

maps/tradeship_alt/tradeship-0.dmm, maps/tradeship_alt/tradeship-1.dmm, maps/tradeship_alt/tradeship-2.dmm, maps/tradeship_alt/tradeship-3.dmm
Adds secrets to Fishfinder (And minor fixes for missing turfs)
A sense of discovery!
CEG
:cl:
add: Secrets. Wouldn't you like to know?
/:cl:
=> The Secret Update

maps/ministation/ministation.dm, mods/species/vox/datum/species.dm
Temporarily re-adding Vox to the selectable races on ministation.
For a special Friday event.
CEG
:cl:
add: Added Vox to selectable ministation species.
/:cl:
=> Temporarily Readding Vox

maps/tradeship_alt/tradeship-1.dmm, maps/tradeship_alt/tradeship-2.dmm
Added Robot Recharging Station to The Bee
Added Cooling Pack to EVA
=> Robot Accessability
