maps/tradeship/tradeship-1.dmm
maps/tradeship/tradeship-2.dmm

- Fixed alarm placement overlapping with apc in research bay
- Removed engineering tape from research doors
- Replaced empty chemical dispenser with full version
- Re-arranged chemical lab
- Re-arranged fabrication bay
- Added robot cryopod to fabrication bay
- Re-arranged research bay
- Removed Ez-nutrimax vendor from research bay
- Removed Seed vendor from research bay
- Added sink to research bay
- Added table, eznutrient and pest killer to hydroponics
- Moved light in reactor room to prevent overlapping wall items
- Moved lightswitch in lower cargo to prevent it weirdly showing up on the upper deck
- Added floral data disk to research bay
- Added plunger to tool storage
- Added nutrient bottles to research bay

Several small changes to tradeship map. 

---

code/game/machinery/kitchen/microwave.dm
code/modules/food/recipes_microwave.dm
code/modules/reagents/reagent_containers/food/snacks.dm

Fixes microwaves breaking/steak only having one codex entry.

---

code/_helpers/text.dm
code/controllers/subsystems/garbage.dm
code/game/machinery/doors/brigdoors.dm
code/game/machinery/supply_display.dm
code/game/objects/items/weapons/paint.dm
code/modules/admin/DB ban/functions.dm
code/modules/emotes/emote_mob.dm
code/modules/flufftext/TextFilters.dm
code/modules/mob/hear_say.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/mob/living/say.dm
code/modules/mob/living/silicon/pai/examine.dm
code/modules/mob/living/silicon/robot/examine.dm
code/modules/mob/mob.dm
code/modules/mob/mob_helpers.dm
code/modules/modular_computers/file_system/programs/security/digitalwarrant.dm
code/modules/organs/blood.dm
code/modules/xenoarcheaology/artifacts/replicator.dm
code/modules/xenoarcheaology/finds/talking.dm

* Handle deprecation warning for `lentext` when compiling with Dream Maker 513.1506 by renaming instances of `lentext` to the recommended `length`
* rename one instance of `lentext` to `cursor_position` to clarify its usage

Update deprecated usage of `lentext`

---

code/game/objects/effects/decals/Cleanable/humans.dm

Most of these are just Bay alien stuff that isn't applicable any more, but a bunch are redundant unused icons (like `paper.dmi` which is replicated in `bureacracy.dmi`).

Removes a bunch of unused icons and images.

---

code/modules/materials/definitions/materials_glass.dm
code/modules/materials/definitions/materials_metal.dm
code/modules/materials/definitions/materials_mineral.dm

- Borosilicate glass is alloyed from glass instead of sand.
- Steel is alloyed from iron instead of hematite.
- Graphite now contains plasticide, rather than smelting to it.
This is foundation work for some simple smelting and alloying machines I'm working on - the convoluted alloying conditions made it impossible to combine smelting and alloying in one operation.

Adjusting smelting and materials to be slightly more straightforward.

---

code/game/gamemodes/events.dm
code/modules/events/radiation_storm.dm
maps/tradeship/tradeship_areas.dm
maps/tradeship/tradeship_define.dm

- Cargo bay, medical bay and dorms on Tradeship are now shielded.
- Radstorm event is more informative about where you can hide.
Closes #100.

Radstorm event tweaks.

---

.travis.yml
test/run-test.sh

the apt pip package is the python2 version of pip which installs all of that noise and generates a deprecation warning since python2 is officially dead come 2020, I guess installing under the user account didn't break anything with the two modules that were installed, they are however necessary.
* Change the travis package requirement from pip to pip3
* Lock python package versions (remember to update those as necessary)

Travis: Move away from using system python by using PyEnv supplied by travis

---

code/controllers/subsystems/garbage.dm

Stack trace is pointless and it spams the hell out of the runtime logs.

Switched GC fail from crash_with to to_world_log. 

---

code/game/objects/effects/decals/Cleanable/fuel.dm
code/modules/ZAS/Fire.dm
code/modules/detectivework/tools/rag.dm
code/modules/reagents/Chemistry-Reagents.dm
code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Core.dm
code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
code/modules/reagents/reagent_containers/food/drinks/bottle.dm

- Reagents now have a `fuel_value` multiplier which determines how many fire stacks they add to targets and how good they are in a Molotov.
- Molotovs and rags can be lit with any flame source, not just `/flame` objects.
- Molotov fire exposure and ignition should be more reliable and intuitive. Hitting a mob or a tile should ignite everything in the turf.
- Molotovs will always smash on being thrown on harm intent, even if you miss your target.
- Fuel decals will now try to descend to the lowest available Z-level before burning.
- Alcohol is now properly flammable and smashing a bottle of vodka over someone's head will make them able to be ignited.
Closes #119.

Molotov cocktail and general fuel reagent refactor.

---

code/modules/clothing/clothing_accessories.dm
code/modules/clothing/suits/storage.dm

Suits with pockets will now have an action button at the top left for opening their storage.
Closes #144.

Adds an action button for suits with pockets.

---

tools/mapmerge2/mapmerge.sh

Default Linux python calls python2. You don't want to override this! Install python3 to make it run properly.

Modifies mapmerge.sh script

---

maps/tradeship/tradeship-1.dmm

- Adds a small light to the robot spawn room
- Dirties the hallway immediately outside the robot spawn room
- Moved a Junior Researcher spawn from xenobotany to fabrication lab
- Rearranged fabrication lab to cut down on running back and forth for RnD
- Moved Integrated Circuit Printer to fabrication lab
- Added a marble desk and window to fabrication lab (much to Jrokko's annoyance, but there is a shutter button)
- Move the cargo bay light switch to a more accessible location

Lower deck map changes

---

maps/tradeship/tradeship_jobs.dm

Enclave Patriarchs did not actually have any access. This seems to be because if the id_type field is missing or using /obj/item/card/id, it doesn't actually get any access!
This is fixed by setting the ID to type /obj/item/card/id/silver, same as the Enclave Matriarch.
The Enclave Patriarch was also moved to the 'head of staff' position for easy reference on the manifest.

Fix Enclave Patriarch access

---

maps/tradeship/tradeship_jobs.dm

Just fixed up Docter to Doctor.
I'm not having any issues playing as the Enclave roles on my machine, is there a server config file that might cause the issue?
To be clear the issue was that the Enclave roles were selectable in character setup but unavailable for actual game play. If you tried to spawn as one you got spawned in as a deck hand and if you tried to late join they would be missing from the selection menu.

Spelling error.

---

baystation12.dme
code/game/objects/items/weapons/storage/trays.dm
code/modules/codex/entries/misc.dm
code/modules/codex/entries/storage.dm

* Changes tray codex stuff to work with this
* Includes basic instructions on how to use storage items too

Adds dynamic codex information for storage items

---

code/game/objects/item.dm
code/modules/mob/inventory.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/human/inventory.dm
code/modules/reagents/reagent_containers/food/snacks.dm

Splitting this off from the Baxxid PR due to issues with Baxxid implementation blocking it.
Basically refactors dexterity to be somewhat more granular and reuses some checks that were previously copypasted boilerplate.

Adjusting item interactions to allow for limited actions by low dexterity humanoids.

---

code/game/objects/items/documents.dm
maps/tradeship/tradeship-0.dmm
maps/tradeship/tradeship-1.dmm
maps/tradeship/tradeship-2.dmm
maps/tradeship/tradeship-3.dmm
maps/tradeship/tradeship_define.dm

* Re-added orebox to lower cargo
* Tidied up some decals in lower cargo
* Removed some pointless tiled turf from solar arrays
* Added new secret documents to bridge (Thanks @ZirconiumWit for flavour text)
* Replaced suit storage units with suit cyclers
* Moved potted bamboo plant in enclave chamber
* Renamed delivery chute to disposal ejection chute
* Added a warning sign to disposal ejection chute
* Changes tradeships steal objectives entirely

Map and steal objective changes

---

code/game/objects/item.dm

Touches on #223 possibly? Managed to drop a backpack by dragging it onto the slot it was currently equipped on.
Closes #222.

Items equipped via drag and drop should respect holders better now.

---

code/unit_tests/icon_tests.dm

Deletes the random spawner icon checks. I don't know why they specifically need a unit test, and it constantly fails Travis builds for reasons that don't seem real.

Removes a consistently unreliable and low priority unit test.

---

code/game/objects/item.dm
code/game/objects/items/weapons/stunbaton.dm
code/modules/crafting/_crafting_holder.dm
code/modules/crafting/_crafting_stage.dm
code/modules/crafting/crafting_recipes/bot_crafting/crafting_ed209.dm
code/modules/crafting/crafting_recipes/bot_crafting/crafting_farmbot.dm
code/modules/crafting/crafting_recipes/bot_crafting/crafting_floorbot.dm
code/modules/crafting/crafting_recipes/bot_crafting/crafting_janibot.dm
code/modules/crafting/crafting_recipes/bot_crafting/crafting_medibot.dm
code/modules/crafting/crafting_recipes/bot_crafting/crafting_secbot.dm
code/modules/crafting/crafting_recipes/gun_crafting/crafting_cannon.dm
code/modules/crafting/crafting_recipes/gun_crafting/crafting_coilgun.dm
code/modules/crafting/crafting_recipes/gun_crafting/crafting_zipgun.dm
code/modules/crafting/crafting_recipes/improvised_crafting/crafting_butterflyknife.dm
code/modules/crafting/crafting_recipes/improvised_crafting/crafting_crossbow.dm
code/modules/crafting/crafting_recipes/improvised_crafting/crafting_spear_prod.dm

- Examining an in-progress build will show you possible options or products.
- Examining a source item will suggest how you can start a build.
- Order of initial components no longer matters.
No codex entry for recipes yet, and no skill checks in crafting. Still thinking about how it should work.
Related to #244.

Adding some hints to the slapcrafting system.

---

maps/tradeship/tradeship_areas.dm

The background hum is part of the atmos code and isn't a bug - there are no vents in the elevator area, so it doesn't play the hum. Really that should be based on the air zone you're, but that's a rewrite/feature request rather than a fix.
Closes #248.

Fixes sound_env and ambience issues with turbolifts on Tradeship.

---

code/game/machinery/_machines_base/stock_parts/radio/transmitter.dm

The reason this is an optimization is that without range set, _all_ potential listeners, regardless of loc, will attempt to receive the signals.
This version has a high enough setting to work with all away maps on alarms; can't be lowered without subtyping off long-distance versions or making map changes (there are exactly two alarms that need to go above 22, which is sort of the default, so the latter is viable). No guarantee that it won't break some buttons.

Optimization to radio components.

---

maps/tradeship/tradeship-0.dmm
maps/tradeship/tradeship-1.dmm
maps/tradeship/tradeship-2.dmm
maps/tradeship/tradeship-3.dmm
maps/tradeship/tradeship_areas.dm
maps/tradeship/tradeship_jobs.dm

* Two new spawn points for captain spare ID. One on enclave deck and one in a dorm
* Added upper bridge area
* Moved comms to upper bridge
* Added First Mate office to lower bridge, with things in it i dunno go look at it
* Added Poppy to Engineering *Hot Feature*
* Increased First mate paperwork skill one level

Tradeship map changes, mostly

---

code/game/machinery/alarm.dm
code/game/machinery/doors/firedoor.dm

Was going to make this tracked in a more reasonable way, but turns out it doesn't even do anything worth noting. The doors check proc is far less performance sensitive than `receive_signal` is (only called from Topic and Process, latter during rare state transitions).

Removes the concept of area master alarm.

---

maps/tradeship/tradeship-0.dmm
maps/tradeship/tradeship-1.dmm
maps/tradeship/tradeship-2.dmm
maps/tradeship/tradeship-3.dmm

Map changes - more detail than necessary included because I'm new at this and want to be a bit thorough.  
*Light switch added to solar array access.  Deleted non-functional light switch frame.
*Added box of monkey cubes to laundry room where some scav intended to perform cube related experimentation
*Ore processing console repositioned for functionality (was non-functional before), density set to 0
*Large airlock access switches (inside and outside) repositioned so as to become functional.  Time to vent some scavs
*Gee, first mate, why does your dev let you have two light switches?  Deleted second light switch in First mate's office
*Moved light switch away from ladder in docking bay
*light switch added to hydroponics
*light switches added to research rooms

Monkey Cube Addition

---

maps/tradeship/tradeship_areas.dm
maps/tradeship/tradeship_jobs.dm

* Jr Scientist on tradeship now forced to have full sciencey access even on minimal access settings
* Solar Array Access area requires Engine access
* EVA now requires EVA access
Resolves #274

Access changes to Jr Scientist, Solar access and EVA

---

code/modules/crafting/_crafting_holder.dm

Hoping to get ahead on some of these material dupe bugs and clean the code up a bit in the process.
- The default deconstruction tool for structures is now welding torch for metal objects, and crowbar for others. It used to be wrench or welding torch depending on item.
- This also applies to removing the plating from simple walls (reinforced walls are still a mess).
- You can now examine a structure to see if it can be unanchored or deconstructed. I haven't added additional checks to specific structures so it won't tell you what other conditions are needed though.
- Reinforcing girders is now done by using a stack on it while it is unanchored. 
- Removing reinforcement is still screwdriver.
- You can use a screwdriver on an un-reinforced girder to toggle whether or not it will form a …

Generalizes some structure tool interactions.

---

code/modules/codex/categories/category_fusion_reaction.dm

Fixes [this part](https://github.com/ScavStation/Baystation12/issues/302#issuecomment-582140814) of #302 
- Fusion products show up properly in the codex.

Makes products show up properly in fusion reaction codex

---

code/game/objects/items/weapons/material/twohanded.dm
code/modules/codex/entries/weapons.dm
code/modules/crafting/crafting_recipes/improvised_crafting/crafting_spear_prod.dm

* Javelins do more damage when thrown or used with one hand, in comparison to spears, but do less damage when held with two hands
* Javelins are made by using wirecutters on a spear
* Resolves #153

Added short version of spears that small mobs can hold

---

code/datums/trading/food.dm
code/modules/food/recipes_microwave.dm
code/modules/mob/living/carbon/taste.dm
code/modules/reagents/reagent_containers/food/snacks.dm

* Removing branding, changing description, changing flavours. Mostly destroys baylore, memes and references.
* Does not change paths or reagent effects
* Removes wingfangchu
* Removes boiled slime core due to a lack of icon

Edits to many snack objects

---

code/modules/scavstation_shared_content/_scavs.dme
code/modules/scavstation_shared_content/map/culturebaxxid.dm
code/modules/scavstation_shared_content/map/languagebaxxid.dm
code/modules/scavstation_shared_content/species/baxxid.dm
maps/tradeship/tradeship.dm

Summary:
- Added Baxxid language, culture/faction.
- Edited files necessary to implement.
Commit log:
Feb. 28, 2020
- Changed language keybind from "b" to "x" in languagebaxxid.dm (line 7)
- Removed autogenerated content in _scavs.dme (line 23 to end of file)
- Removed "/datum/language/baxxid" from baxxid.dm (line 37)
- Moved autohiss in baxxid.dm (lines 39 & 40)
- Changed definition of CULTURE_BAXXID from "Baxxid" to "Baxxid Clans" in tradeship.dm (line 12)
Feb. 27, 2020
- Created culturebaxxid.dm (Baxxid culture & faction)
- Created languagebaxxid.dm (Baxxid language)
- Added Baxxid culture & faction to baxxid.dm (lines 31 thru 37)
- Added autohiss exemption to baxxid.dm (lines 49 thru 50)
- Added filepaths to _scavs.dme (lines 14 thru 15)
- Added definitions to tradeship.dm (lines 11 …

Baxxid culture/language

---

maps/tradeship/tradeship-0.dmm
maps/tradeship/tradeship-1.dmm
maps/tradeship/tradeship-2.dmm

* Added newscasters to various rooms on the ship
* Replaced spear on enclave deck with javelin
* Increased amount of skill books that spawn in compartment 2-B
* Added salvage voidsuit to engineering storage

Tradeship map: More newscasters and misc

---

maps/tradeship/outfits/command.dm
maps/tradeship/tradeship-1.dmm
maps/tradeship/tradeship-2.dmm
maps/tradeship/tradeship-3.dmm

* Fixes #456 (Captain and F. Mate not having access)
* Tidies up network machines a bit to provide actual coverage
* (Currently machines may still need manual network connecting due to non-map bug)
Should specify with machines:
Router and mainframe are in telecomms now.
Relays in F. Mate office, spooky's grand archives, tool storage

Fixes #456 and small tradeship map changes

---

maps/ministation/ministation.dmm
maps/ministation/ministation_objects.dm

* Adds randomized medical supplies to commons
* Adds two budget insulated gloves to commons
* Assistant vending machines have multitool as contraband
* Replaced emergency space suits in EVA with real space suits
* Fixes maint access to cargo

Ministation map tweaks

---

maps/ministation/ministation.dmm
maps/ministation/ministation_define.dm
maps/ministation/ministation_objects.dm
maps/ministation/ministation_telecomms.dm

* Adds several yinglet jumpsuits around the map (and a librarian robe)
* Fixes camera networks
* Does NOT fix AI being blind, sorry.

Ministation map tweaks: yingsuits and camera fix

---

mods/valsalia/species/indrel.dm

Because apparently they're supposed to be? Also helps the poor head engineers that can't equip voidsuits.

Makes indrel immune to damage from vacuum

---

maps/away/liberia/liberia.dmm

swaps ion thrusters with rockets
Ion thrusters are broken, this lets liberia/mule move.
Devcord
:cl:
tweak: thruster types on liberia/mule
/:cl:

libera thruster changes

---

code/modules/mob/living/carbon/breathe.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/carbon/carbon_defines.dm
code/modules/mob/living/carbon/human/human_powers.dm
code/modules/mob/living/living.dm
code/modules/mob/living/living_defines.dm

Adds simple breath-holding functionality. Not entirely balanced but better than nothing.
Without this, anyone without an oxygen tank and mask or immediate medical attention is physically unable to move through any amount of toxic gas without dying, regardless of whether or not they know it's there, easily trapping someone into being unable to interact with the round. While this will definitely need changes later on, it is best that this scenario not happen in the meantime.
Alceris
:cl:
add: Added ability to hold your breath.
/:cl:

Adds simple breath-holding functionality.

---

maps/away/liberia/liberia.dmm
maps/away/liberia/liberia_areas.dm
maps/away_sites_testing/away_sites_testing.dm
maps/tradeship/tradeship-0.dmm
mods/valsalia/items/voidsuits.dm

Added in two new voidsuits, one for Liberia merchants, and another for the yinglet matriarch
Yinglets aboard the liberia can actually do their job now, and the Yinglet Matriarch will finally have a voidsuits that displays her status
Devchord
:cl:
add: Added a small merchant voidsuit and a small matriarch voidsuit
add: Added the merchant voidsuit to 5 lockers on the Liberia and the matriarch voidsuit to a single locker on tradeship
/:cl:

More yingsuits

---

maps/away/bearcat/bearcat-1.dmm
maps/away/bearcat/bearcat-2.dmm

add yingsuits to the bearcat away map, plus a few minor other QoL tweaks (few more nitrogen canisters)
Lets Yinglets survive on the away map, and the extra canisters will let the ship actually be fully pressurized again if atmost is repaired.
Qumefox
:cl:
add: yingsuits to bearcat away map
/:cl:

Bearcat away map scavification

---

maps/tradeship/tradeship-2.dmm
maps/tradeship/tradeship_overmap.dm

Added missing docking point to the docking list
lets the rescue shuttle dock properly to tradeship
Qumefox
:cl:
fix: rescue shuttle docking
/:cl:

fixed rescue shuttle docking

---

maps/away/bearcat/bearcat_areas.dm
maps/tradeship/tradeship-0.dmm
maps/tradeship/tradeship_areas.dm

Changes tradeship and bridge area names, and adds holopad in enclave
Bridge holopads on bearcat and tradeship couldn't talk to each other due to having the same area name, and thus, same holopad name.
A holopad for enclave level was also requested
:cl:
add: Added enclave holopad
tweak: area names
/:cl:

fixed area names to remove holopad duplicates

---

maps/ministation/jobs/civilian.dm
maps/ministation/jobs/security.dm
maps/ministation/ministation.dmm
maps/ministation/ministation_define.dm
maps/ministation/ministation_jobs.dm
maps/ministation/outfits/medical.dm
maps/ministation/outfits/security.dm

removed the extra fire alarm in rep office
non-ying job availability has been restored (except for humans and baxxid)
robo lathe has been added to R&D
detective outfit and access has been reworked
traitor theft items are obtainable
less filth to account for persistence
now you can have 2 cooks
general fixes for issues found on ministation
Devchord
:cl:
add: Added robo lathe to R&D
del: Removed 2nd fire alarm in the representatives office
del: Removed excessive filth
tweak: tweaked barista to have 2 available roles
balance: rebalanced detective role to account for low pop
fix: fixed inavailability of jobs for non-human species
fix: traitor theft targets that were missing were added in
spellcheck: squashed another "personell"
/:cl:

Ministationfixes11192022

---

code/modules/webhooks/webhook_fax_sent.dm

Actually naming the webhook properly across all scripts
because sent != send...
Qumefox
:cl:
fix: webhook names
/:cl:

Name the new fax webhook properly..

---

maps/ministation/ministation.dmm

Fixed engineering and shuttle airlocks
gave beanbag shells to bar shotgun
added headsets and recoats to hop office
broken airlocks break gameplay
headsets and uniforms help RP
barkeep should not have lethal ammunition
Devchord
:cl:
add: spare headsets and redcoats to hop office
balance: changed shotgun shells in bar to beanbags
fix: fixed typos that broke the engineering and shuttle airlocks
/:cl:

Ministation fixes 121622

---

code/modules/blob/blob.dm

Halves blob health pool across the board.
Lowers blob attack rate slightly.
Lowers blob expansion rate somewhat (hopefully)
Lowers the chance of aux cores spawning as the blob expands.
Slightly decreases fire resistance.
Nerfs blob due to complaints of it being completely unkillable no matter what. Will hopefully make blob events less rage inducing and actually survivable (from a round standpoint)
Qumefox
:cl:
tweak: blob health, fire resistance and expansion rate
/:cl:

Nerfs blob a bit due to complaints

---

maps/ministation/ministation.dmm

Separated the Shuttle sensors from the station sensors
Fixed the shuttles airlocks
Increased chance of having ores spawn in the asteroid cores outside of the station
Makes away missions more bearable as well as making cargo more interesting
Devchord
:cl:
add: Added High_Chance rock walls to the cores of the large asteroids
fix: fixed the airlock cycling for the shuttle
fix: fixed the sensors being linked between the shuttle and the station
/:cl:

Science shuttle fixes and ores

---

maps/ministation2/ministation2.dm
maps/ministation2/ministation_antagonists.dm
maps/ministation2/ministation_areas.dm
maps/ministation2/ministation_define.dm
maps/ministation2/ministation_jobs.dm
maps/ministation2/ministation_unit_testing.dm
mods/valsalia/map/overrides.dm

changed some names to hopefully prevent ministation2 from meshing with ministation
Hopefully fixes the issue found with ministation2
makes the maps able to function independently 
Devchord
:cl:
fix: changes ministation to ministation 2 in a couple of places
/:cl:

define fixes for ministation2

---

mods/valsalia/map/overrides.dm

readds the ministation define in valsalia/overrides.dm
Dev got a little overzealous about swapping ministation to ministation2, and in this file it should have been an addition instead of a replacement
qumefox
:cl:
fix: overrides.dm
/:cl:

readdes the original ministation datum

---

maps/ministation2/jobs/engineering.dm
maps/ministation2/ministation-1.dmm
maps/ministation2/ministation-2.dmm

Added in new alternate title for CE and some extra holopads were added around the station
Added Patriarch of Electricity title for CE
Added holopads to Security and Medbay
RP stuff and AI functionality
Devchord
:cl:
add: Added "Patriarch of Electricity" alternate title to CE
add: Added holopads to Security and Medbay
/:cl:

ministation2 fixes 4/20/23

---

code/game/objects/items/weapons/storage/backpack.dm

Updates bag of holding max item size.
Makes the bag of holding have the same max item size as regular backpacks, since well, it's a backpack.
Qumefox
:cl:
balance: Changes bag of holding max item size
/:cl:

changes bag of holding max item size

---

maps/ministation2/jobs/civilian.dm
maps/ministation2/jobs/command.dm
maps/ministation2/jobs/engineering.dm
maps/ministation2/jobs/medical.dm
maps/ministation2/jobs/science.dm
maps/ministation2/jobs/security.dm
maps/ministation2/jobs/tradehouse.dm
maps/ministation2/ministation-0.dmm
maps/ministation2/ministation-1.dmm
maps/ministation2/ministation-2.dmm

Robot rechargers are now located nearby drone fabricators. Disposal network has been extended. A door has been placed to allow access between the bar and hydro. Some barnacles can now be located on the station hull. Added 10 skill points to each occupation to accommodate low pop rounds. Fixed the missing cargo teleporter
General fixes that will help improve game quality
Devchord
:cl:
add: Added robot rechargers next to drone fabs
add: Added more chutes to the disposal network
add: Added barnacles to the exterior hull
add: Added door between bar and hydro
balance: added 10 skillpoints to each role
fix: fixed missing teleporter pad for cargo
/:cl:

Ministation2fixes 5 17 23

---

maps/ministation2/ministation-0.dmm
maps/ministation2/ministation-2.dmm

Moved cargo tiplod spawn in cargo to fix hitch bug, placeholder medical pouches in R&D replaced with trauma pouches
Just general bug fixes
Devchord
:cl:
fix: fixed cargo tiplod spawn position
fix: fixed placeholder medical pouches being accessible
/:cl:

Ministationfixes 6 1 23

---

mods/valsalia/items/suit_cycler.dm

Replacing overriding suit cycler bodytype options with appending yinglet bodytype to the original list.
Before: allegedly sometimes suit cycler allows only human and yinglet bodytypes to refit to.
After: suit cycler allows human, yinglet and avain bodytypes.
Myself.
:cl:
refactor: fixed the suit cycler refitting bodytypes list
/:cl:

Suit cycler override/extend bodytypes list fix

---

maps/random_ruins/exoplanet_ruins/crashed_pod/crashed_pod.dm
maps/random_ruins/exoplanet_ruins/crashed_pod/crashed_pod.dmm

Replaces crashed escape pod away site with a modernized version
Mostly gives the crashed pod a proper airlock, as well as rearranging the internal structure to be more space efficient. Overall footprint did not change.
Qumefox
:cl:
add: Replaced crashed escape pod away site
/:cl:

modernizes crashed escape pod

---

maps/ministation2/ministation-1.dmm

-Security's weapons have been sorted into another, greater chamber with several deterrents to restrict access to ballistic lethals -More alternatives for non-lethal options, which are placed behind the first layer of armory -Replacement ammunition for the detective's sidearm and energy guns to issue to heads of staff in the event of minor threats and laser carbines for minor to medium threats are placed in the second layer. 
-Lethal ballistics meant for away missions, high to delta level threats, mechs and special orders given by the Trademaster are housed within in the third layer under watch of a motion sensitive camera and turrets, a Patriarch of Security or station Matriarch are permitted within these walls and a **standing order for the station artificial intelligence** is to seek …

Secure Update

---

code/modules/blob/blob.dm

Looks like Qume applied the nerf under the assumption the resistance was a multiplier, but it is a divisor. This should fix blobs being resistant to fire.

Reapplies blob fire vulnerability nerfs, renames vars for clarity.

---

maps/ministation2/ministation2.dm
maps/tradeship/tradeship.dm

Removes the includes for Vox from both our normal maps.
Vox shouldn't really be playable.
Qumefox
:cl:
del: Vox includes
/:cl:

Removes vox includes from mollusc and tradeship

---

maps/random_ruins/exoplanet_ruins/crashed_pod/crashed_pod.dm
maps/random_ruins/exoplanet_ruins/crashed_pod/crashed_pod.dmm

Just as it says on the tin.  Mostly fixes misaligned things like air alarms and the plaque, and adds another light to 'engineering'
because these were floating in the walkways
Qumefox
:cl:
tweak: tweaked a few things about the survival pod
/:cl:

Fixes some issues with the crashed pod

---

maps/ministation2/ministation_overmap.dm
maps/tradeship/tradeship_overmap.dm

removes start coord defines for tradeship and mollusc
stops tradeship and mollusc from always starting at 4:4
Qumefox
:cl:
tweak: map start coords
/:cl:

Removes overmap start defines for tradeship and mollusc

---

code/game/antagonist/station/traitor.dm

…ong with telecrystals and proper messages for what code words are and stored to memory
The pull request is to add methods so that candidates who become traitor mid round are properly equiped with an uplink and given the code phrases that are saved to memory. This only procs for both the original traitor(s) and the candidate(s) if one of the candidate(s) becomes a mid round traitor.
There was a bug noted that the mid round traitor was not being given neither the code words nor uplink and could not be of use to the traitor as they had no way of contacting or helping.
EvilDrCoconut
:cl:
bugfix: fixed a few things
/:cl:

Fixed traitor issues, late addded traitors should get uplink and code words

---

maps/ministation2/outfits/civilian.dm
maps/ministation2/outfits/engineering.dm
maps/ministation2/outfits/medical.dm
maps/ministation2/outfits/science.dm
maps/ministation2/outfits/security.dm
mods/valsalia/items/clothing_yinglet.dm
mods/valsalia/jobs/yinglet_job.dm

Readjusts the redcoat variants used on ministation2 to match lore
Immersion
Devchord
:cl:
tweak: tweaked the redcoat variants used for most jobs
imageadd: added missing yinglet equivilents of each redcoat
code: changed the yinglet redcoat fallback code to account for the new variants
/:cl:

ministation2-fixes-2-14-2024

---

code/controllers/configuration.dm

pulls mistakenot's traitor round fixes
so rounds other than extended can be chosen
MistakeNot4892
:cl:
bugfix: fixed traitor round selections
/:cl:

traitor round fix

---

maps/ministation2/ministation-1.dmm
maps/ministation2/ministation-2.dmm
maps/ministation2/ministation-3.dmm

Microlathe added for the bartender, Missing voidsuits were readded to R&D's EVA, Fixed the leak in the north west maint corridor
This will make the map function as well as make bar RP better, also science will be able to organize away teams
Devchord
:cl:
add: Added voidsuits to science eva lockers
add: Added microlathe to bar
bugfix: fixed missing tiles above the maint corridors
/:cl:

Ministation2 fixes 2 19 2024

---

code/modules/reagents/chems/chems_drinks.dm
code/modules/reagents/reactions/reaction_recipe.dm
maps/_map_include.dm
maps/ministation/ministation-0.dmm
maps/ministation/ministation-1.dmm
maps/ministation/ministation-2.dmm
maps/ministation/ministation_areas.dm

-Added new drinks Pilk and Horchata
-Added nursery room to medbay
-Added trashbag costumes (including shiny trashbag!) to map
-Added avian smocks to lockers in medbay, engineering, and security
-Expanded medbay-research stairway area
-Various minor mapping tweaks
More drinks are always good
Aleuph requested the nursery, its better to have the eggs in medbay than in a room with a nuclear bomb
Trashbag costumes were created ages ago, but were inaccessible due to not being present on maps
There was previously no mapped avian clothing
Medbay-research stairway area is very cramped, this has caused serious z-level lag due to the crowd-crush
Various tweaks such as access to previously unmapped vendor types, reduction of resources in medbay, better surgery-spectating
:cl:
add: Pilk and recipe …

New drinks, map changes

---

maps/ministation/ministation-0.dmm
maps/ministation/ministation-1.dmm
maps/ministation/ministation-2.dmm
maps/ministation/ministation-3.dmm

moved science server room
added lunch area to science
opened up access to science lobby, added doorway blocking access to rest of science
added handbars to sides of shuttle cockpit (previously if you climbed on the table in the cockpit, there was no way to buckle in, and if someone was in the seat you couldnt leave so you took damage on landing)
added laser charger to shuttle
added ominous vault door leading to mass driver
shifted mass driver and bomb range 3 tiles to the east
fixed missing oxygen piping to xenoarchaology
fixed misplaced light in maint north of dorms
changed tile to blank floor under stairway to bomb range stairwell, to mitigate popin
moved science apc into science lobby
rearranged items in the captains quarters for ease of use
rearranged items on medbay tables for ease …

Minor tweaks to (mostly) science

---

maps/random_ruins/exoplanet_ruins/crashed_pod/crashed_pod.dmm
maps/random_ruins/exoplanet_ruins/playablecolony/colony.dmm

fixed some ID issues on exterior colony airlock vents. Added sensors to crashed pod to help it cycle appropriately/add to the experience/thoroughness' sake.

Fixes to airlocks on colony/crashed pod

---

maps/ministation/ministation-0.dmm
maps/ministation/ministation-1.dmm
maps/ministation/ministation-2.dmm
maps/ministation/ministation-3.dmm
maps/ministation/ministation_areas.dm

- Added Enclave Table Room (??? it has a table and big windows, what do you want from me???) 
- Made the clown and goose more talkative (hopefully!) 
- Added cheery decorations to the clown's room (yay!) 
- Spraypainted everyone's impossible dreams gold (snazzy!) 
- made the Bast Fastard red (it's the fastest colour you know!) 
- Added commemorative clown toys to medical (because if you work there, you'll definitely prefer a toy clown over the real deal!) 
- Found Gikka's Lost Pen (yay)
- Lost Gikka's Pen (aw)
- Probably broke the Enclave airlock even more (YAY) 
- Gave names to a couple critters (they so fuzzy!)
- Added more tube things to trans your its to the place be am what of (probably!) 
- Enclave tower got stairs (OO FANCY)
- Spookums is now a Yingksy brand, like that one sock …

Final meaningful Enclave update (for now!); some tweaks to Yingksy installations

---

maps/ministation/ministation-2.dmm

fixed the ticlag issue, clowns no longer have a non-standard step size variable

Update ministation-2.dmm (zoomy ticlag fix)

---

maps/random_ruins/exoplanet_ruins/crashed_pod/crashed_pod.dmm
maps/random_ruins/exoplanet_ruins/playablecolony/colony.dmm

Attempting a partial fix for Pod airlock, tank is now empty so when it vents internal atmosphere, it will at least quickly fill instead of hang when trying to exit. Still looking into solutions for external entry hang, however.
Colony airlock now has three vents each for internal and external pressure. Internal venting will be a bit slower, but external venting should be faster now too.
Fixed a couple locks in the Hydroponics bay on Colony. No more smashing lockers to get farm tools.

Tweaks to Colony and Pod away sites

---

mods/valsalia/map/overrides.dm

removes submap species restrictions from valsalia\map\overrides.dm
lets you spawn on away missions as any species
:cl:
bugfix: fixed a few things
/:cl:

remove species whitelist from valsal overrides

---

mods/valsalia/species/baxxid.dm

An oversight when altering the baxxid dexterity is that they could now use guns and other firearms, which unbalances them compared to other ingame species. AND-NOT-ing DEXTERITY_FULL with DEXTERITY_WEAPONS appears to fix this issue. Melee tools such as the crowbar or katana seem to still function from testing it on a private server.

Remove the ability for baxxid to use guns/firearms.

---

mods/valsalia/species/baxxid.dm

Baxxid are unable to wear space suits and it seems other species incapable of doing so are typically given space resistance--in particular the "serpentids" here (though other codebases with other species seem to follow this general rule as well), see [mods/species/serpentid/datum/species.dm:natural_armour_values].

Add natural baxxid space resistance, so they can do their jobs.

---

mods/valsalia/species/baxxid.dm

Added natural amount of insulation so basic wiring can be done with only mild--moderate burns at most, rather than severe and deadly ones which cause the unfortunate baxxid to collapse and die.
The baxxid species size was set to large but their ambient strength was still set to the same value as a default human for some reason--changed from 'STR_MEDIUM' to 'STR_HIGH'.
Added slight radiation protection, which when tested is less effective than wearing a radiation suit (which the baxxid species can not fit into currently). Makes it possible for baxxid to work in slightly radioactive regions without suffering guaranteed fatal radiation poisoning.
Altered blood volume and hunger depletion to more (at least, in my opinion) accurately represent their size, as by default they have the same …

Tweak baxxid species stats.

---

ministation-1.dmm

Redecorates ministation-1 by adding grass, pathways, and painted tiles in order to add to the visual experience.
The intent is to make the station look a little less barren visually, and add to the atmosphere.
All those who worked on Ministation prior.
CEG (me) for recent decorations.
:cl: Cegmeister
Added grass to the Level 2 hallways
Added stone pathways to the Level 2 hallways
Added red decals to the dining lounge
Added dark monotiles and mahogany tiling to security
Added white monotiles to medical
/:cl:

The Mollusc Greenery Update

---

maps/ministation/ministation-1.dmm
maps/ministation/ministation-2.dmm

Fixed some decal misalignment and re-added the cooking pot and skillet on ministation-1, redesigned the bridge and speakeasy on ministation-2
Makes medical less disgusting to look at, makes stew a meal you can cook in the kitchen, and makes the speakeasy look somehow more abandoned than it was.
Anyone who worked on Ministation beforehand.
:cl: Cegmeister
add: Added skillet and cooking pot to the kitchen
add: Added decals and awful ugly floors to bridge and speakeasy respectively
tweak: Fixed the decals in Medbay
/:cl:

Ministation Fixes

---

code/modules/surgery/_surgery.dm

Fixes an issue where if the surgeon was wearing a thick material on a body part, they would be unable to perform surgery on a patient even if the patient wasn't wearing anything.
Also added to the failure message a section that explains what item is blocking the surgery, removing guesswork.
Line 151 of code/modules/surgery/_surgery.dm incorrectly checked `user.get_covering_equipped_item_by_zone(target_zone)` instead of `target.get_covering_equipped_item_by_zone(target_zone)`.
Line 153 has been modified to add "`(\the [I.name])`" to the failure message regarding the material being too thick to do surgery through.  This removes guesswork by letting the surgeon know exactly what item needs to be removed in order to proceed.
Surgery was strange and inconsistent previously, with being randomly …

Fix surgery checking surgeon's body covered instead of patient's

---

code/modules/mob/living/living_breath.dm

The check was backwards so you only breathed out when holding your breath.

Fix exhaling not working when not holding your breath

---

maps/random_ruins/exoplanet_ruins/hateville/hateville.dmm
maps/random_ruins/exoplanet_ruins/summit/summit.dmm

- Reduced the number of Proselytizing Corporatists by 1/2 on the Overrun Colony (Hateville) map.
- Reduced overall number of mobs from 38 to 23 on the Summit map.

Summit, Overrun Colony (Hateville) mob counts reduced.

---

maps/ministation/ministation-1.dmm

fixing an issue by replacing telecoms dark tiles with regular dark tiles (telecomms variant naturally cools area)
Will stop lag when water or drinks enter the area, lol
SpentAppleRods
:cl:
bugfix: fixed a few things
/:cl:

fixed constant tile freeze issue

---

maps/away/liberia/liberia.dmm

Fixed mule airlock so it works the same as the science shuttle
Playability fixes to Liberia away site
:cl:
bugfix: fixed Mule airlock
tweak: moved the Mule's airlock buttons, fuel tank, and ATMs to more sensible locations
add: added minor junk items to the slots where the Mule atms were previously
tweak: changed the Liberia's money bag to be a pre-filled variant instead of an empty variant and a loose pile of cash
/:cl:

Fixed Mule airlock

---

maps/ministation/jobs/civilian.dm

Standardizes the cargo access to always include both maint and EVA.
The access was a little borked considering the minimal version had more access than the normal one. Devcord confirmed this on discord.
Tabski
:cl:
tweak: Ministation cargo technicians will now always have access to maint and EVA
/:cl:

Standardize ministation cargo tech access

---

maps/random_ruins/exoplanet_ruins/summit/summit.dm
mods/valsalia/species/languageOldYing.dm

Summit explosion description tweaks.
Important 'zhe' words added to Old Yinglish (remember, 'zhe' is a new ying-ism compared to 'the'! Probably. idk.)

Wordening fixes
